### ISSUE TITLE
Link to Causal Inference Resources

### ISSUE THREAD

**Issue by ddsjoberg** [LucyMcGowan/user2020-causal-inference#4]
Hello hello! Thank you for these lovely causal inference materials!

A colleague of mine is writing a short vignette on propensity score analyses using gtsummary. We are including a section for additional resources.
1. Do you mind if we link people to this repo?
2. Is there a another resource you've created you'd prefer we link to?

Thanks!

**Comment by malcolmbarrett** [comment]
This is our more up-to-date repo: https://github.com/malcolmbarrett/causal_inference_r_workshop. Feel free!

**Comment by ddsjoberg** [comment]
Thank you!
